#! /usr/bin/env python
# encoding: utf-8
#
# Flare Flash Driver
#

import buildcontrol

sources = [
    'flash.c',
]

board_sources = {
    'versal': [
        'versal-flash.c',
    ],
    'zynqmp': [
        'zynqmp-flash.c',
    ],
    'zynq7000': [
        'zynq7000-flash.c',
    ]
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources + buildcontrol.board_source(bld, board_sources)
    bld.objects(target='flare_flash_driver', features='c', source=srcs)


def format(bld):
    srcs = sources + buildcontrol.board_source(bld, board_sources, True)
    buildcontrol.format(bld, srcs)
