#! /usr/bin/env python
# encoding: utf-8
#
# Flare MD5 Driver
#

sources = [
    'md5.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_md5_driver', features='c', source=sources)
