#! /usr/bin/env python
# encoding: utf-8
#
# Flare SLCR Driver
#

sources = []

board_sources = {
    'versal': [
        'empty-slcr.c',
    ],
    'zynqmp': [
        'empty-slcr.c',
    ],
    'zynq7000': [
        'zynq7000-slcr.c',
    ]
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_slcr_driver', features='c', source=srcs)
