#! /usr/bin/env python
# encoding: utf-8
#
# Flare JFFS2 Driver
#

sources = ['jffs2-boot.c', 'libcrc32.c']


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_jffs2_driver', features='c', source=sources)
