#! /usr/bin/env python
# encoding: utf-8
#
# Flare GPIO Driver
#

import buildcontrol

sources = [
    'gpio.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_gpio_driver', features='c', source=sources)


def format(bld):
    srcs = sources + ['gpio.h']
    buildcontrol.format(bld, srcs)
