#! /usr/bin/env python
# encoding: utf-8
#
# Flare GPIO Driver
#

sources = [
    'gpio.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_gpio_driver', features='c', source=sources)
