#! /usr/bin/env python
# encoding: utf-8
#
# Flare AARCH64 Support
#

sources = [
    'aarch64-atf.c',
    'aarch64-cache.c',
    'aarch64-error.c',
    'aarch64-flare.c',
    'aarch64-fsbl-boot-start.S',
    'aarch64-handoff.S',
    'aarch64-handoff.c',
    'mmu/aarch64-cache.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_arch', features='c', source=sources)
