#! /usr/bin/env python
# encoding: utf-8
#
# Xilinx BOOT.BIN partitions Driver
#

import buildcontrol

sources = []

board_sources = {
    'versal': [],
    'zynqmp': [
        'xpartition.c',
    ],
    'zynq7000': []
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_xpartition_driver', features='c', source=srcs)


def format(bld):
    srcs = sources + buildcontrol.board_source(bld, board_sources, True)
    buildcontrol.format(bld, srcs)
