#! /usr/bin/env python
# encoding: utf-8
#
# Flare IO Driver
#

import buildcontrol


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass


def format(bld):
    buildcontrol.format(bld, ['board-io.h'])
