#! /usr/bin/env python
# encoding: utf-8
#
# Flare zlib Driver
#

import buildcontrol

sources = ['tzlib.c']


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_zlib_driver', features='c', source=sources)


def format(bld):
    srcs = sources + ['tzlib.c']
    buildcontrol.format(bld, srcs)
