#! /usr/bin/env python
# encoding: utf-8
#
# Flare Bootloader Filesystems
#

sources = [
    'boot-filesystem.c',
    'jffs2-filesystem.c',
    'fatfs-filesystem.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_fs', features='c', source=sources)
