#! /usr/bin/env python
# encoding: utf-8
#
# Flare Board Support
#

import buildcontrol

directories = [
    'zynq7000',
    'zynqmp',
]


def init(ctx):
    buildcontrol.recurse(ctx, directories)


def options(opt):
    buildcontrol.recurse(opt, directories)


def configure(conf):
    buildcontrol.recurse(conf, directories)


def build(bld):
    buildcontrol.recurse(bld, [bld.env.FLARE_BOARD])
