#! /usr/bin/env python
# encoding: utf-8
#
# Flare UART Driver
#

sources = [
    'outbyte.c',
    'inbyte.c',
]

board_sources = {
    'versal': [
        'versal-uart.c',
    ],
    'zynqmp': [
        'zynqmp-uart.c',
    ],
    'zynq7000': [
        'zynq7000-uart.c',
    ]
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_uart_driver', features='c', source=srcs)
