#! /usr/bin/env python
# encoding: utf-8
#
# Flare Baremetal Libc Driver
#

sources = [
    'libc.c',
    'printf.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_libc_driver', features='c', source=sources)
