#! /usr/bin/env python
# encoding: utf-8
#
# Flare ZYNQMP Support
#

import buildcontrol

sources = [
    'zynqmp-boot-plan.c',
    'zynqmp-datasafe.c',
    'zynqmp-mmu.c',
    'zynqmp-vectors.S',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_board', features='c', source=sources)


def format(bld):
    srcs = sources + ['zynqmp.h', 'zynqmp-flash-map.h']
    srcs.remove('zynqmp-mmu.c')
    buildcontrol.format(bld, srcs)
