#! /usr/bin/env python
# encoding: utf-8
#
# Flare ZYNQMP Support
#

sources = [
    'zynqmp-boot-plan.c',
    'zynqmp-datasafe.c',
    'zynqmp-mmu.c',
    'zynqmp-vectors.S',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_board', features='c', source=sources)
