#! /usr/bin/env python
# encoding: utf-8
#
# Flare FATFS Driver
#

import buildcontrol

sources = [
    'ff.c',
    'ffsystem.c',
    'ffunicode.c',
    'sdwrapper.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_fatfs_driver',
                features='c',
                source=sources,
                includes=['.'])


def format(bld):
    srcs = ['sdwrapper.c', 'sdwrapper.h']
    buildcontrol.format(bld, srcs)
