#! /usr/bin/env python
# encoding: utf-8
#
# Flare CRC Driver
#

sources = [
    'crc.c',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_crc_driver', features='c', source=sources)
