#! /usr/bin/env python
# encoding: utf-8
#
# Flare Power Switch Driver
#

sources = []

board_sources = {
    'versal': [
        'empty-power-switch.c',
    ],
    'zynqmp': [
        'empty-power-switch.c',
    ],
    'zynq7000': [
        'zynq7000-power-switch.c',
    ]
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_power_switch_driver', features='c', source=srcs)
