#! /usr/bin/env python
# encoding: utf-8
#
# Flare ZYNQ7000 Support
#

sources = [
    'zynq7000-begin-lo.S',
    'zynq7000-boot-plan.c',
    'zynq7000-cache.c',
    'zynq7000-datasafe.c',
    'zynq7000-error.c',
    'zynq7000-handoff.c',
    'zynq7000-mmu.c',
    'zynq7000_vectors.S',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_board', features='c', source=sources)
