#! /usr/bin/env python
# encoding: utf-8
#
# Flare Timer Driver
#

sources = [
    'usleep.c',
]

board_sources = {
    'versal': [
        'versal-timer.c',
    ],
    'zynqmp': [
        'zynqmp-timer.c',
    ],
    'zynq7000': [
        'zynq7000-timer.c',
    ]
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_timer_driver', features='c', source=srcs)
