#! /usr/bin/env python
# encoding: utf-8
#
# Flare PM Driver
#

sources = []

board_sources = {
    'versal': [],
    'zynqmp': [
        'ipi.c',
        'pm.c',
        'pm_cfg_obj.c',
    ],
    'zynq7000': []
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_pm_driver', features='c', source=srcs)
