#! /usr/bin/env python
# encoding: utf-8
#
# Flare ARM Support
#

sources = [
    'arm-fsbl-boot-start.S',
    'cpu_init.S',
    'crt0.S',
]


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_arch',
                features='c',
                source=sources,
                use=['flare_xilinx'])
