#! /usr/bin/env python
# encoding: utf-8
#
# Flare Bootloader
#

import buildcontrol

directories = [
    'driver',
    'fs',
    'arch',
    'board',
]

sources = [
    'board-handoff.c',
    'boot-buffer.c',
    'boot-factory-config.c',
    'boot-load.c',
    'boot-script.c',
    'datasafe.c',
    'factory-boot.c',
    'reset.c',
    'user-break.c',
]


def init(ctx):
    buildcontrol.recurse(ctx, directories)


def options(opt):
    buildcontrol.recurse(opt, directories)
    copts = opt.get_option_group('configure options')
    copts.add_option('--no-handoff',
                     action='store_true',
                     help='Disable handoff for debugging')
    copts.add_option('--boot-delay',
                     type=int,
                     dest='boot_delay',
                     default=2,
                     help='Set the boot delay in seconds (defaut: %(default)s)')


def configure(conf):
    buildcontrol.recurse(conf, directories)
    if conf.options.no_handoff:
        conf.env.DEFINES += ['FLARE_HANDOFF_DISABLE=1']
        conf.msg('Handoff', 'no')
    else:
        conf.env.DEFINES += ['FLARE_HANDOFF_DISABLE=0']
        conf.msg('Handoff', 'yes')
    conf.env.DEFINES += ['FLARE_BOOT_DELAY={0}'.format(conf.options.boot_delay)]
    conf.msg('Boot delay', '{} seconds'.format(conf.options.boot_delay))


def build(bld):
    buildcontrol.recurse(bld, directories)
    uses = ['flare_fs', 'flare_arch', 'flare_board'] + bld.env.FLARE_USE
    bld.stlib(target='flare',
              features='c',
              source=sources,
              use=uses)
