#! /usr/bin/env python
# encoding: utf-8
#
# Flare WatchDog Driver
#

sources = []

board_sources = {
    'versal': [],
    'zynqmp': [
        'empty-wdog.c',
        'wdog-empty.c',
    ],
    'zynq7000': ['zynq7000-wdog.c', 'wdog-flare_1.c']
}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    srcs = sources
    if bld.env.FLARE_BOARD in board_sources:
        srcs += board_sources[bld.env.FLARE_BOARD]
    bld.objects(target='flare_wdog_driver', features='c', source=srcs)
